[SFPA-38] AsymmetricCollectionDemo UI tests
scalefocus/SFPortfolioApp pull request #49
Opened 2021-08-31 12:34 UTC by stoikokolev

2021-09-01 11:11 UTC, ODimitrovSF approved these changes

2021-09-02 08:22 UTC, plamenzhl requested changes

2021-09-02 08:22 UTC, plamenzhl commented on SFPortfolioApp/SFPortfolioAppUITests/DemoModuleTests/AsymmetricCollectionView/AsymmetricCollectionViewDemoSceneTests.swift
> +        // When
// Given is missing

2021-09-02 09:59 UTC, stoikokolev commented on SFPortfolioApp/SFPortfolioAppUITests/DemoModuleTests/AsymmetricCollectionView/AsymmetricCollectionViewDemoSceneTests.swift
> +        // When
Fixed

2021-09-02 13:20 UTC, plamenzhl approved these changes

2021-09-02 13:56 UTC, merged